export type StockMarket = 'cac40' | 'sbf120' | 'sp500' | 'nasdaq' | 'other';

export interface StockPresetItem {
  symbol: string;
  name: string;
  category: 'index' | 'stock' | 'crypto' | 'forex' | 'commodity';
  market?: StockMarket;
}

// 1. Major Indices
export const MAJOR_INDICES: StockPresetItem[] = [
  { symbol: '^FCHI', name: 'CAC 40', category: 'index', market: 'cac40' },
  { symbol: '^SBF120', name: 'SBF 120', category: 'index', market: 'sbf120' },
  { symbol: '^GSPC', name: 'S&P 500', category: 'index', market: 'sp500' },
  { symbol: '^IXIC', name: 'Nasdaq Composite', category: 'index', market: 'nasdaq' },
  { symbol: '^NDX', name: 'Nasdaq 100', category: 'index', market: 'nasdaq' },
  { symbol: '^DJI', name: 'Dow Jones', category: 'index', market: 'sp500' },
  { symbol: '^GDAXI', name: 'DAX 40', category: 'index' },
  { symbol: '^STOXX50E', name: 'Euro Stoxx 50', category: 'index' },
  { symbol: '^FTSE', name: 'FTSE 100', category: 'index' },
  { symbol: '^N225', name: 'Nikkei 225', category: 'index' },
];

// 2. Top 20 Cryptos
export const TOP_20_CRYPTO: StockPresetItem[] = [
  { symbol: 'BTC-USD', name: 'Bitcoin', category: 'crypto' },
  { symbol: 'ETH-USD', name: 'Ethereum', category: 'crypto' },
  { symbol: 'SOL-USD', name: 'Solana', category: 'crypto' },
  { symbol: 'BNB-USD', name: 'BNB', category: 'crypto' },
  { symbol: 'XRP-USD', name: 'XRP (Ripple)', category: 'crypto' },
  { symbol: 'ADA-USD', name: 'Cardano', category: 'crypto' },
  { symbol: 'AVAX-USD', name: 'Avalanche', category: 'crypto' },
  { symbol: 'DOGE-USD', name: 'Dogecoin', category: 'crypto' },
  { symbol: 'DOT-USD', name: 'Polkadot', category: 'crypto' },
  { symbol: 'LINK-USD', name: 'Chainlink', category: 'crypto' },
  { symbol: 'NEAR-USD', name: 'NEAR Protocol', category: 'crypto' },
  { symbol: 'SUI-USD', name: 'Sui', category: 'crypto' },
  { symbol: 'SHIB-USD', name: 'Shiba Inu', category: 'crypto' },
  { symbol: 'LTC-USD', name: 'Litecoin', category: 'crypto' },
  { symbol: 'BCH-USD', name: 'Bitcoin Cash', category: 'crypto' },
  { symbol: 'UNI-USD', name: 'Uniswap', category: 'crypto' },
  { symbol: 'PEPE-USD', name: 'Pepe', category: 'crypto' },
  { symbol: 'APT-USD', name: 'Aptos', category: 'crypto' },
  { symbol: 'RENDER-USD', name: 'Render', category: 'crypto' },
  { symbol: 'XLM-USD', name: 'Stellar', category: 'crypto' },
];

// 3. CAC 40 Constituents (40 Actions)
export const CAC40_CONSTITUENTS: StockPresetItem[] = [
  { symbol: 'AIR.PA', name: 'Airbus', category: 'stock', market: 'cac40' },
  { symbol: 'AI.PA', name: 'Air Liquide', category: 'stock', market: 'cac40' },
  { symbol: 'ALO.PA', name: 'Alstom', category: 'stock', market: 'cac40' },
  { symbol: 'MT.AS', name: 'ArcelorMittal', category: 'stock', market: 'cac40' },
  { symbol: 'CS.PA', name: 'AXA', category: 'stock', market: 'cac40' },
  { symbol: 'BNP.PA', name: 'BNP Paribas', category: 'stock', market: 'cac40' },
  { symbol: 'ENGI.PA', name: 'Engie', category: 'stock', market: 'cac40' },
  { symbol: 'EL.PA', name: 'EssilorLuxottica', category: 'stock', market: 'cac40' },
  { symbol: 'RMS.PA', name: 'Hermès', category: 'stock', market: 'cac40' },
  { symbol: 'KER.PA', name: 'Kering', category: 'stock', market: 'cac40' },
  { symbol: 'OR.PA', name: "L'Oréal", category: 'stock', market: 'cac40' },
  { symbol: 'MC.PA', name: 'LVMH', category: 'stock', market: 'cac40' },
  { symbol: 'ML.PA', name: 'Michelin', category: 'stock', market: 'cac40' },
  { symbol: 'ORA.PA', name: 'Orange', category: 'stock', market: 'cac40' },
  { symbol: 'RI.PA', name: 'Pernod Ricard', category: 'stock', market: 'cac40' },
  { symbol: 'PUB.PA', name: 'Publicis', category: 'stock', market: 'cac40' },
  { symbol: 'RNO.PA', name: 'Renault', category: 'stock', market: 'cac40' },
  { symbol: 'SAF.PA', name: 'Safran', category: 'stock', market: 'cac40' },
  { symbol: 'SGO.PA', name: 'Saint-Gobain', category: 'stock', market: 'cac40' },
  { symbol: 'SAN.PA', name: 'Sanofi', category: 'stock', market: 'cac40' },
  { symbol: 'SU.PA', name: 'Schneider Electric', category: 'stock', market: 'cac40' },
  { symbol: 'GLE.PA', name: 'Société Générale', category: 'stock', market: 'cac40' },
  { symbol: 'STMPA.PA', name: 'STMicroelectronics', category: 'stock', market: 'cac40' },
  { symbol: 'TEP.PA', name: 'Teleperformance', category: 'stock', market: 'cac40' },
  { symbol: 'HO.PA', name: 'Thales', category: 'stock', market: 'cac40' },
  { symbol: 'TTE.PA', name: 'TotalEnergies', category: 'stock', market: 'cac40' },
  { symbol: 'URW.AS', name: 'Unibail-Rodamco-Westfield', category: 'stock', market: 'cac40' },
  { symbol: 'VIE.PA', name: 'Veolia', category: 'stock', market: 'cac40' },
  { symbol: 'DG.PA', name: 'Vinci', category: 'stock', market: 'cac40' },
  { symbol: 'CAP.PA', name: 'Capgemini', category: 'stock', market: 'cac40' },
  { symbol: 'CA.PA', name: 'Carrefour', category: 'stock', market: 'cac40' },
  { symbol: 'ACA.PA', name: 'Crédit Agricole', category: 'stock', market: 'cac40' },
  { symbol: 'BN.PA', name: 'Danone', category: 'stock', market: 'cac40' },
  { symbol: 'DSY.PA', name: 'Dassault Systèmes', category: 'stock', market: 'cac40' },
  { symbol: 'EDEN.PA', name: 'Edenred', category: 'stock', market: 'cac40' },
  { symbol: 'LR.PA', name: 'Legrand', category: 'stock', market: 'cac40' },
  { symbol: 'VIV.PA', name: 'Vivendi', category: 'stock', market: 'cac40' },
  { symbol: 'STLA.PA', name: 'Stellantis', category: 'stock', market: 'cac40' },
  { symbol: 'BVI.PA', name: 'Bureau Veritas', category: 'stock', market: 'cac40' },
  { symbol: 'SW.PA', name: 'Sodexo', category: 'stock', market: 'cac40' },
];

// 4. SBF 120 Extra Constituents (French Mid/Large Caps)
export const SBF120_EXTRA_CONSTITUENTS: StockPresetItem[] = [
  { symbol: 'AMUN.PA', name: 'Amundi', category: 'stock', market: 'sbf120' },
  { symbol: 'ATO.PA', name: 'Atos', category: 'stock', market: 'sbf120' },
  { symbol: 'BB.PA', name: 'BIC', category: 'stock', market: 'sbf120' },
  { symbol: 'BIM.PA', name: 'BioMérieux', category: 'stock', market: 'sbf120' },
  { symbol: 'BOL.PA', name: 'Bolloré', category: 'stock', market: 'sbf120' },
  { symbol: 'CARM.PA', name: 'Carmila', category: 'stock', market: 'sbf120' },
  { symbol: 'COFA.PA', name: 'Coface', category: 'stock', market: 'sbf120' },
  { symbol: 'COV.PA', name: 'Covivio', category: 'stock', market: 'sbf120' },
  { symbol: 'DEC.PA', name: 'JCDecaux', category: 'stock', market: 'sbf120' },
  { symbol: 'DBG.PA', name: 'Derichebourg', category: 'stock', market: 'sbf120' },
  { symbol: 'ELI.PA', name: 'Elis', category: 'stock', market: 'sbf120' },
  { symbol: 'ERA.PA', name: 'Eramet', category: 'stock', market: 'sbf120' },
  { symbol: 'ERF.PA', name: 'Eurofins Scientific', category: 'stock', market: 'sbf120' },
  { symbol: 'ETL.PA', name: 'Eutelsat Communications', category: 'stock', market: 'sbf120' },
  { symbol: 'FDJ.PA', name: 'La Française des Jeux', category: 'stock', market: 'sbf120' },
  { symbol: 'FGR.PA', name: 'Eiffage', category: 'stock', market: 'sbf120' },
  { symbol: 'GFC.PA', name: 'Gecina', category: 'stock', market: 'sbf120' },
  { symbol: 'GET.PA', name: 'Getlink', category: 'stock', market: 'sbf120' },
  { symbol: 'GTT.PA', name: 'Gaztransport & Technigaz', category: 'stock', market: 'sbf120' },
  { symbol: 'ICAD.PA', name: 'Icade', category: 'stock', market: 'sbf120' },
  { symbol: 'IDIP.PA', name: 'ID Logistics', category: 'stock', market: 'sbf120' },
  { symbol: 'IPS.PA', name: 'Ipsos', category: 'stock', market: 'sbf120' },
  { symbol: 'KOF.PA', name: 'Kaufman & Broad', category: 'stock', market: 'sbf120' },
  { symbol: 'LI.PA', name: 'Klépierre', category: 'stock', market: 'sbf120' },
  { symbol: 'MF.PA', name: 'Wendel', category: 'stock', market: 'sbf120' },
  { symbol: 'NEX.PA', name: 'Nexans', category: 'stock', market: 'sbf120' },
  { symbol: 'NXI.PA', name: 'Nexity', category: 'stock', market: 'sbf120' },
  { symbol: 'OPM.PA', name: 'OPmobility', category: 'stock', market: 'sbf120' },
  { symbol: 'OVH.PA', name: 'OVHcloud', category: 'stock', market: 'sbf120' },
  { symbol: 'PLUX.PA', name: 'Pluxee', category: 'stock', market: 'sbf120' },
  { symbol: 'RCO.PA', name: 'Rémy Cointreau', category: 'stock', market: 'sbf120' },
  { symbol: 'RUI.PA', name: 'Rubis', category: 'stock', market: 'sbf120' },
  { symbol: 'SK.PA', name: 'SEB', category: 'stock', market: 'sbf120' },
  { symbol: 'SOI.PA', name: 'Soitec', category: 'stock', market: 'sbf120' },
  { symbol: 'SOP.PA', name: 'Sopra Steria', category: 'stock', market: 'sbf120' },
  { symbol: 'SPIE.PA', name: 'SPIE', category: 'stock', market: 'sbf120' },
  { symbol: 'TE.PA', name: 'Technip Energies', category: 'stock', market: 'sbf120' },
  { symbol: 'TF1.PA', name: 'TF1', category: 'stock', market: 'sbf120' },
  { symbol: 'TFI.PA', name: 'Television Française 1', category: 'stock', market: 'sbf120' },
  { symbol: 'TRI.PA', name: 'Trigano', category: 'stock', market: 'sbf120' },
  { symbol: 'UBI.PA', name: 'Ubisoft Entertainment', category: 'stock', market: 'sbf120' },
  { symbol: 'VAC.PA', name: 'Vallourec', category: 'stock', market: 'sbf120' },
  { symbol: 'VAP.PA', name: 'Valneva', category: 'stock', market: 'sbf120' },
  { symbol: 'VIRP.PA', name: 'Virbac', category: 'stock', market: 'sbf120' },
  { symbol: 'VRAP.PA', name: 'Verallia', category: 'stock', market: 'sbf120' },
  { symbol: 'WLN.PA', name: 'Worldline', category: 'stock', market: 'sbf120' },
  { symbol: 'ALST.PA', name: 'Alten', category: 'stock', market: 'sbf120' },
  { symbol: 'SESG.PA', name: 'SES-imagotag (VusionGroup)', category: 'stock', market: 'sbf120' },
  { symbol: 'EXENS.PA', name: 'Exail Technologies', category: 'stock', market: 'sbf120' },
  { symbol: 'MAU.PA', name: 'Maurel & Prom', category: 'stock', market: 'sbf120' },
];

// 5. S&P 500 Top & Leading Constituents (US Large Caps)
export const SP500_CONSTITUENTS: StockPresetItem[] = [
  { symbol: 'AAPL', name: 'Apple', category: 'stock', market: 'sp500' },
  { symbol: 'MSFT', name: 'Microsoft', category: 'stock', market: 'sp500' },
  { symbol: 'NVDA', name: 'NVIDIA', category: 'stock', market: 'sp500' },
  { symbol: 'AMZN', name: 'Amazon', category: 'stock', market: 'sp500' },
  { symbol: 'GOOGL', name: 'Alphabet (Google)', category: 'stock', market: 'sp500' },
  { symbol: 'META', name: 'Meta Platforms', category: 'stock', market: 'sp500' },
  { symbol: 'TSLA', name: 'Tesla', category: 'stock', market: 'sp500' },
  { symbol: 'BRK-B', name: 'Berkshire Hathaway', category: 'stock', market: 'sp500' },
  { symbol: 'AVGO', name: 'Broadcom', category: 'stock', market: 'sp500' },
  { symbol: 'JPM', name: 'JPMorgan Chase', category: 'stock', market: 'sp500' },
  { symbol: 'LLY', name: 'Eli Lilly', category: 'stock', market: 'sp500' },
  { symbol: 'V', name: 'Visa', category: 'stock', market: 'sp500' },
  { symbol: 'UNH', name: 'UnitedHealth Group', category: 'stock', market: 'sp500' },
  { symbol: 'XOM', name: 'Exxon Mobil', category: 'stock', market: 'sp500' },
  { symbol: 'MA', name: 'Mastercard', category: 'stock', market: 'sp500' },
  { symbol: 'PG', name: 'Procter & Gamble', category: 'stock', market: 'sp500' },
  { symbol: 'COST', name: 'Costco Wholesale', category: 'stock', market: 'sp500' },
  { symbol: 'HD', name: 'Home Depot', category: 'stock', market: 'sp500' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', category: 'stock', market: 'sp500' },
  { symbol: 'WMT', name: 'Walmart', category: 'stock', market: 'sp500' },
  { symbol: 'ABBV', name: 'AbbVie', category: 'stock', market: 'sp500' },
  { symbol: 'BAC', name: 'Bank of America', category: 'stock', market: 'sp500' },
  { symbol: 'NFLX', name: 'Netflix', category: 'stock', market: 'sp500' },
  { symbol: 'KO', name: 'Coca-Cola', category: 'stock', market: 'sp500' },
  { symbol: 'CRM', name: 'Salesforce', category: 'stock', market: 'sp500' },
  { symbol: 'ORCL', name: 'Oracle', category: 'stock', market: 'sp500' },
  { symbol: 'CVX', name: 'Chevron', category: 'stock', market: 'sp500' },
  { symbol: 'MRK', name: 'Merck & Co.', category: 'stock', market: 'sp500' },
  { symbol: 'PEP', name: 'PepsiCo', category: 'stock', market: 'sp500' },
  { symbol: 'AMD', name: 'AMD', category: 'stock', market: 'sp500' },
  { symbol: 'LIN', name: 'Linde', category: 'stock', market: 'sp500' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific', category: 'stock', market: 'sp500' },
  { symbol: 'MCD', name: "McDonald's", category: 'stock', market: 'sp500' },
  { symbol: 'CSCO', name: 'Cisco Systems', category: 'stock', market: 'sp500' },
  { symbol: 'ADBE', name: 'Adobe', category: 'stock', market: 'sp500' },
  { symbol: 'ABT', name: 'Abbott Laboratories', category: 'stock', market: 'sp500' },
  { symbol: 'QCOM', name: 'Qualcomm', category: 'stock', market: 'sp500' },
  { symbol: 'IBM', name: 'IBM', category: 'stock', market: 'sp500' },
  { symbol: 'GE', name: 'General Electric', category: 'stock', market: 'sp500' },
  { symbol: 'CAT', name: 'Caterpillar', category: 'stock', market: 'sp500' },
  { symbol: 'TXN', name: 'Texas Instruments', category: 'stock', market: 'sp500' },
  { symbol: 'DIS', name: 'Walt Disney', category: 'stock', market: 'sp500' },
  { symbol: 'VZ', name: 'Verizon', category: 'stock', market: 'sp500' },
  { symbol: 'INTC', name: 'Intel', category: 'stock', market: 'sp500' },
  { symbol: 'WFC', name: 'Wells Fargo', category: 'stock', market: 'sp500' },
  { symbol: 'PM', name: 'Philip Morris', category: 'stock', market: 'sp500' },
  { symbol: 'MS', name: 'Morgan Stanley', category: 'stock', market: 'sp500' },
  { symbol: 'GS', name: 'Goldman Sachs', category: 'stock', market: 'sp500' },
  { symbol: 'PLTR', name: 'Palantir Technologies', category: 'stock', market: 'sp500' },
  { symbol: 'UBER', name: 'Uber Technologies', category: 'stock', market: 'sp500' },
  { symbol: 'NOW', name: 'ServiceNow', category: 'stock', market: 'sp500' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', category: 'stock', market: 'sp500' },
  { symbol: 'AMAT', name: 'Applied Materials', category: 'stock', market: 'sp500' },
  { symbol: 'BKNG', name: 'Booking Holdings', category: 'stock', market: 'sp500' },
  { symbol: 'AXP', name: 'American Express', category: 'stock', market: 'sp500' },
  { symbol: 'PFE', name: 'Pfizer', category: 'stock', market: 'sp500' },
  { symbol: 'NKE', name: 'Nike', category: 'stock', market: 'sp500' },
  { symbol: 'LOW', name: "Lowe's", category: 'stock', market: 'sp500' },
  { symbol: 'BA', name: 'Boeing', category: 'stock', market: 'sp500' },
  { symbol: 'RTX', name: 'RTX Corporation', category: 'stock', market: 'sp500' },
  { symbol: 'HON', name: 'Honeywell', category: 'stock', market: 'sp500' },
  { symbol: 'SPGI', name: 'S&P Global', category: 'stock', market: 'sp500' },
  { symbol: 'BLK', name: 'BlackRock', category: 'stock', market: 'sp500' },
  { symbol: 'LRCX', name: 'Lam Research', category: 'stock', market: 'sp500' },
  { symbol: 'GILD', name: 'Gilead Sciences', category: 'stock', market: 'sp500' },
  { symbol: 'PANW', name: 'Palo Alto Networks', category: 'stock', market: 'sp500' },
  { symbol: 'MU', name: 'Micron Technology', category: 'stock', market: 'sp500' },
  { symbol: 'KLAC', name: 'KLA Corporation', category: 'stock', market: 'sp500' },
  { symbol: 'ADI', name: 'Analog Devices', category: 'stock', market: 'sp500' },
  { symbol: 'SNPS', name: 'Synopsys', category: 'stock', market: 'sp500' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', category: 'stock', market: 'sp500' },
  { symbol: 'CRWD', name: 'CrowdStrike', category: 'stock', market: 'sp500' },
  { symbol: 'DE', name: 'Deere & Company', category: 'stock', market: 'sp500' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', category: 'stock', market: 'sp500' },
  { symbol: 'SYK', name: 'Stryker', category: 'stock', market: 'sp500' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', category: 'stock', market: 'sp500' },
  { symbol: 'MDLZ', name: 'Mondelez International', category: 'stock', market: 'sp500' },
  { symbol: 'ETN', name: 'Eaton Corporation', category: 'stock', market: 'sp500' },
  { symbol: 'BSX', name: 'Boston Scientific', category: 'stock', market: 'sp500' },
  { symbol: 'C', name: 'Citigroup', category: 'stock', market: 'sp500' },
  { symbol: 'CB', name: 'Chubb', category: 'stock', market: 'sp500' },
  { symbol: 'MMC', name: 'Marsh & McLennan', category: 'stock', market: 'sp500' },
  { symbol: 'ANET', name: 'Arista Networks', category: 'stock', market: 'sp500' },
  { symbol: 'SCHW', name: 'Charles Schwab', category: 'stock', market: 'sp500' },
  { symbol: 'ADP', name: 'Automatic Data Processing', category: 'stock', market: 'sp500' },
  { symbol: 'EQIX', name: 'Equinix', category: 'stock', market: 'sp500' },
  { symbol: 'CME', name: 'CME Group', category: 'stock', market: 'sp500' },
  { symbol: 'WM', name: 'Waste Management', category: 'stock', market: 'sp500' },
  { symbol: 'ICE', name: 'Intercontinental Exchange', category: 'stock', market: 'sp500' },
  { symbol: 'SHW', name: 'Sherwin-Williams', category: 'stock', market: 'sp500' },
];

// 6. Nasdaq 100 Constituents (Tech & Growth)
export const NASDAQ_CONSTITUENTS: StockPresetItem[] = [
  { symbol: 'AAPL', name: 'Apple', category: 'stock', market: 'nasdaq' },
  { symbol: 'MSFT', name: 'Microsoft', category: 'stock', market: 'nasdaq' },
  { symbol: 'NVDA', name: 'NVIDIA', category: 'stock', market: 'nasdaq' },
  { symbol: 'AMZN', name: 'Amazon', category: 'stock', market: 'nasdaq' },
  { symbol: 'GOOGL', name: 'Alphabet Class A', category: 'stock', market: 'nasdaq' },
  { symbol: 'GOOG', name: 'Alphabet Class C', category: 'stock', market: 'nasdaq' },
  { symbol: 'META', name: 'Meta Platforms', category: 'stock', market: 'nasdaq' },
  { symbol: 'TSLA', name: 'Tesla', category: 'stock', market: 'nasdaq' },
  { symbol: 'AVGO', name: 'Broadcom', category: 'stock', market: 'nasdaq' },
  { symbol: 'COST', name: 'Costco Wholesale', category: 'stock', market: 'nasdaq' },
  { symbol: 'ASML', name: 'ASML Holding', category: 'stock', market: 'nasdaq' },
  { symbol: 'NFLX', name: 'Netflix', category: 'stock', market: 'nasdaq' },
  { symbol: 'AMD', name: 'AMD', category: 'stock', market: 'nasdaq' },
  { symbol: 'PEP', name: 'PepsiCo', category: 'stock', market: 'nasdaq' },
  { symbol: 'LIN', name: 'Linde', category: 'stock', market: 'nasdaq' },
  { symbol: 'CSCO', name: 'Cisco Systems', category: 'stock', market: 'nasdaq' },
  { symbol: 'ADBE', name: 'Adobe', category: 'stock', market: 'nasdaq' },
  { symbol: 'TMUS', name: 'T-Mobile US', category: 'stock', market: 'nasdaq' },
  { symbol: 'QCOM', name: 'Qualcomm', category: 'stock', market: 'nasdaq' },
  { symbol: 'INTU', name: 'Intuit', category: 'stock', market: 'nasdaq' },
  { symbol: 'AMGN', name: 'Amgen', category: 'stock', market: 'nasdaq' },
  { symbol: 'TXN', name: 'Texas Instruments', category: 'stock', market: 'nasdaq' },
  { symbol: 'ISRG', name: 'Intuitive Surgical', category: 'stock', market: 'nasdaq' },
  { symbol: 'CMCSA', name: 'Comcast', category: 'stock', market: 'nasdaq' },
  { symbol: 'HON', name: 'Honeywell', category: 'stock', market: 'nasdaq' },
  { symbol: 'AMAT', name: 'Applied Materials', category: 'stock', market: 'nasdaq' },
  { symbol: 'BKNG', name: 'Booking Holdings', category: 'stock', market: 'nasdaq' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals', category: 'stock', market: 'nasdaq' },
  { symbol: 'LRCX', name: 'Lam Research', category: 'stock', market: 'nasdaq' },
  { symbol: 'PANW', name: 'Palo Alto Networks', category: 'stock', market: 'nasdaq' },
  { symbol: 'GILD', name: 'Gilead Sciences', category: 'stock', market: 'nasdaq' },
  { symbol: 'MU', name: 'Micron Technology', category: 'stock', market: 'nasdaq' },
  { symbol: 'ADI', name: 'Analog Devices', category: 'stock', market: 'nasdaq' },
  { symbol: 'KLAC', name: 'KLA Corporation', category: 'stock', market: 'nasdaq' },
  { symbol: 'SNPS', name: 'Synopsys', category: 'stock', market: 'nasdaq' },
  { symbol: 'CDNS', name: 'Cadence Design Systems', category: 'stock', market: 'nasdaq' },
  { symbol: 'CRWD', name: 'CrowdStrike', category: 'stock', market: 'nasdaq' },
  { symbol: 'MDLZ', name: 'Mondelez International', category: 'stock', market: 'nasdaq' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals', category: 'stock', market: 'nasdaq' },
  { symbol: 'ADP', name: 'Automatic Data Processing', category: 'stock', market: 'nasdaq' },
  { symbol: 'MELI', name: 'MercadoLibre', category: 'stock', market: 'nasdaq' },
  { symbol: 'PDD', name: 'PDD Holdings', category: 'stock', market: 'nasdaq' },
  { symbol: 'MAR', name: 'Marriott International', category: 'stock', market: 'nasdaq' },
  { symbol: 'CTAS', name: 'Cintas', category: 'stock', market: 'nasdaq' },
  { symbol: 'ORLY', name: "O'Reilly Automotive", category: 'stock', market: 'nasdaq' },
  { symbol: 'NXPI', name: 'NXP Semiconductors', category: 'stock', market: 'nasdaq' },
  { symbol: 'FTNT', name: 'Fortinet', category: 'stock', market: 'nasdaq' },
  { symbol: 'PCAR', name: 'PACCAR', category: 'stock', market: 'nasdaq' },
  { symbol: 'MNST', name: 'Monster Beverage', category: 'stock', market: 'nasdaq' },
  { symbol: 'PAYX', name: 'Paychex', category: 'stock', market: 'nasdaq' },
  { symbol: 'ADSK', name: 'Autodesk', category: 'stock', market: 'nasdaq' },
  { symbol: 'CPRT', name: 'Copart', category: 'stock', market: 'nasdaq' },
  { symbol: 'ROST', name: 'Ross Stores', category: 'stock', market: 'nasdaq' },
  { symbol: 'ODFL', name: 'Old Dominion Freight Line', category: 'stock', market: 'nasdaq' },
  { symbol: 'LULU', name: 'Lululemon Athletica', category: 'stock', market: 'nasdaq' },
  { symbol: 'FAST', name: 'Fastenal', category: 'stock', market: 'nasdaq' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper', category: 'stock', market: 'nasdaq' },
  { symbol: 'DXCM', name: 'DexCom', category: 'stock', market: 'nasdaq' },
  { symbol: 'VRSK', name: 'Verisk Analytics', category: 'stock', market: 'nasdaq' },
  { symbol: 'EXC', name: 'Exelon', category: 'stock', market: 'nasdaq' },
  { symbol: 'BKR', name: 'Baker Hughes', category: 'stock', market: 'nasdaq' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories', category: 'stock', market: 'nasdaq' },
  { symbol: 'GEHC', name: 'GE HealthCare', category: 'stock', market: 'nasdaq' },
  { symbol: 'ON', name: 'ON Semiconductor', category: 'stock', market: 'nasdaq' },
  { symbol: 'MCHP', name: 'Microchip Technology', category: 'stock', market: 'nasdaq' },
  { symbol: 'FANG', name: 'Diamondback Energy', category: 'stock', market: 'nasdaq' },
  { symbol: 'KHC', name: 'Kraft Heinz', category: 'stock', market: 'nasdaq' },
  { symbol: 'MRVL', name: 'Marvell Technology', category: 'stock', market: 'nasdaq' },
  { symbol: 'CSX', name: 'CSX Corporation', category: 'stock', market: 'nasdaq' },
  { symbol: 'CTSH', name: 'Cognizant Technology Solutions', category: 'stock', market: 'nasdaq' },
  { symbol: 'ILMN', name: 'Illumina', category: 'stock', market: 'nasdaq' },
  { symbol: 'TEAM', name: 'Atlassian', category: 'stock', market: 'nasdaq' },
  { symbol: 'ZS', name: 'Zscaler', category: 'stock', market: 'nasdaq' },
  { symbol: 'DDOG', name: 'Datadog', category: 'stock', market: 'nasdaq' },
  { symbol: 'ARM', name: 'ARM Holdings', category: 'stock', market: 'nasdaq' },
  { symbol: 'WDAY', name: 'Workday', category: 'stock', market: 'nasdaq' },
  { symbol: 'ABNB', name: 'Airbnb', category: 'stock', market: 'nasdaq' },
  { symbol: 'DASH', name: 'DoorDash', category: 'stock', market: 'nasdaq' },
  { symbol: 'COIN', name: 'Coinbase Global', category: 'stock', market: 'nasdaq' },
  { symbol: 'MSTR', name: 'MicroStrategy', category: 'stock', market: 'nasdaq' },
  { symbol: 'APP', name: 'AppLovin', category: 'stock', market: 'nasdaq' },
  { symbol: 'TTD', name: 'The Trade Desk', category: 'stock', market: 'nasdaq' },
  { symbol: 'SNOW', name: 'Snowflake', category: 'stock', market: 'nasdaq' },
];

// Combined list of all presets
export const ALL_STOCK_PRESETS: StockPresetItem[] = [
  ...MAJOR_INDICES,
  ...TOP_20_CRYPTO,
  ...CAC40_CONSTITUENTS,
  ...SBF120_EXTRA_CONSTITUENTS,
  ...SP500_CONSTITUENTS,
  ...NASDAQ_CONSTITUENTS,
].filter((item, index, self) => index === self.findIndex((t) => t.symbol.toUpperCase() === item.symbol.toUpperCase()));

export function resolvePresetInfo(symbol: string): StockPresetItem | undefined {
  const clean = symbol.trim().toUpperCase();
  return ALL_STOCK_PRESETS.find((p) => p.symbol.toUpperCase() === clean);
}
